---
- name: Check disk usage
  hosts: all
  become: yes

  tasks:
    - name: Get disk usage
      ansible.builtin.shell: df -h /
      register: disk_usage

    - name: Show disk usage
      ansible.builtin.debug:
        msg: "{{ disk_usage.stdout_lines }}"
