- name: Get and display hostname of target
  hosts: all  # or specify your target hosts
  gather_facts: yes  # This is essential for gathering system facts

  tasks:
    - name: Display hostname
      debug:
        msg: "The hostname of the target is {{ ansible_hostname }}"
