---
- name: Update all packages on all hosts
  hosts: all
  become: yes  # Ensure that all tasks run with elevated privileges
  tasks:
    - name: Update package list and upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update all packages (Red Hat/CentOS/Fedora)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update all packages (Fedora)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "Fedora"
