---
- name: Update Twingate Connector
  hosts: all
  become: yes

  vars:
    package_name: twingate-connector

  tasks:
    - name: Update apt package manager cache (Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure the latest version of the Twingate Connector is installed (Debian-based systems)
      apt:
        name: "{{ package_name }}"
        state: latest
      when: ansible_os_family == "Debian"

    - name: Ensure the latest version of the Twingate Connector is installed (Red Hat-based systems)
      yum:
        name: "{{ package_name }}"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Check if Twingate Connector service is running
      service:
        name: twingate-connector
        state: started
      ignore_errors: yes

    - name: Restart Twingate Connector service if updated
      service:
        name: twingate-connector
        state: restarted
      when: service_result.changed
