---
- name: Update Twingate Connector
  hosts: all
  become: yes  # Become root to perform system updates
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: Upgrade Twingate Connector if an update is available
      ansible.builtin.apt:
        name: twingate-connector
        state: latest
        force_apt_get: yes
      when: update_result.changed

    - name: Restart Twingate Connector service to apply the update
      ansible.builtin.service:
        name: twingate-connector
        state: restarted
      when: update_result.changed
