---
- name: Update all packages on Ubuntu/Debian systems
  hosts: all
  become: yes  # Use sudo to become root, required for installing updates

  tasks:
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600  # Update the cache if it's older than 1 hour

  - name: Upgrade all packages to the latest version
    ansible.builtin.apt:
      upgrade: dist
